DATA_PATH = r".\data\raw\*.csv"

TOP_DOMAIN_USAGES = 100
DOMAIN_COUNT_THRESHOLD = 1

NUMBER_OF_QUERIES_EACH_CHUNK = 750
NUMBER_OF_USERS = 15
LEARNING_USERS = 10
TEST_UESR = 5

LEARNING_CHUNKS = 50
TESTING_CHUNKS = 40
USEABLE_CHUNKS = LEARNING_CHUNKS + TESTING_CHUNKS

COMMON_DOMAIN_COUNT = 100